---
- name: Ensure local_ssh_path exists {{ local_ssh_path }}
  local_action: file path={{ local_ssh_path }} state=directory # owner={{ sc_owner }} group={{ sc_group }} mode={{ sc_mode }}
  become: false
  tags:
    - always

- name: Pull SSH Config files from server to local
  fetch: src={{ ssh_path_remote }}/{{ item }} dest={{ local_ssh_path }}/{{ item }} flat=yes
  become: true
  with_items: "{{ssh_config_files}}"
  when: do_pull == true
  tags:
    - pull

- name: Push SSH Config files from local to server
  copy: src={{ local_ssh_path }}/{{ item }} dest={{ ssh_path_remote }}/{{ item }}
  become: true
  with_items:
    "{{ssh_config_files}}"
  when:
    - do_push == true
  tags:
    - push
